version: 0.2

env:
  variables:
    S3_BUCKET: portfolio.architectwithappu.online
    CLOUDFRONT_DIST_ID: E32QEKO4CGJ7WR
    BUILD_DIR: dist

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
    # Install project dependencies
      - node -v
      - npm -v
      - echo "Installing pnpm..."
      - npm install -g pnpm
      - echo "Installing dependencies..."
      - pnpm install --frozen-lockfile

  pre_build:
    commands:
      - echo "Cleaning previous build artifacts..."
      - rm -rf $BUILD_DIR

  build:
    commands:
      - echo "Running build..."
      - pnpm run build

  post_build:
    commands:
      # - echo "Syncing new build to S3 (removing stale files)..."
      
      # # 1. Upload static assets with long-term caching (hashed files)
      # - aws s3 sync $BUILD_DIR s3://$S3_BUCKET --delete --exclude "index.html" --cache-control "public,max-age=31536000,immutable"

      # # 2. Upload index.html separately with no-cache (critical for SPA updates)
      # - aws s3 cp $BUILD_DIR/index.html s3://$S3_BUCKET/index.html --cache-control "no-cache, no-store, must-revalidate"

      # - echo "Creating optimized CloudFront invalidation..."

      # Only invalidate entry points instead of full cache (cost-efficient)
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/index.html" "/"

artifacts:
  base-directory: dist
  files:
    - '**/*'
cache:
  paths:
    # Cache node_modules to speed up subsequent builds
    - 'node_modules/**/*'